### ISSUE TITLE
Adding a child to another component during an animation throws error

### ISSUE THREAD

**Issue by koko236** [chenglou/react-motion#221] opened 2015-10-18 15:55 UTC
I have the following (simplified) structure:
```
    <DumbWrapperComponent>
      <Messages/>  (listens to MesagesStore)
      <OtherUI/>     (listens to UIStore)
    </DumbWrapperComponent>
```
Messages and OtherUI have two distinct stores they're listening to, so they (should) render independently of each other. OtherUI has some draggable elements using ReactMotion for smooth animation and an 'Add Message' button which adds a message to Messages using Flux pattern. It all works fine except for a case when you click the 'Add Message' button quickly after dragging something so the animation is still running. I get "Error: Invariant Violation: Expected flush transaction's stored dirty-components length (1) to match dirty-components array length (2)"

I'm going to check it more thoroughly in a second and update/close if I find the solution but I thought I'd ask just as a sanity check - is this an expected and known behavior/limitation of React Motion? 

I'm still using v0.2.7 if that matters.

**Comment by chenglou** [comment] 2015-10-18 16:21
Eh, that's weird and I'm not totally sure what you mean by it. That you're adding components inside messages? Yeah that shouldn't interfere.

(Also, update to 0.3.1 when you can! Just in case =P)

**Comment by koko236** [comment] 2015-10-18 18:10
Yeah, I'm adding `Message` components inside `Messages` comp which has common parent with the `OtherUI` component. React Motion animations run under `OtherUI` node. `OtherUI` and `Messages` listen to two separate stores. The only connections are:  

1. single button a few levels under  `OtherUI` which calls `MessageActions.addMessage()`, which in turn informs `MessagesStore` via `EventDispatcher` and then again `Messages` component is updated by `CHANGED` event - so nothing very tight.
2. common React comp parent - alas a dumb one - no state, no updates, just a container really. 

The call stack however starts with ReactMotion loop() function which might or might not mean something:
![screen shot 2015-10-18 at 20 01 33](https://github-cloud.s3.amazonaws.com/assets/741399/10565541/393da4f0-75d3-11e5-8931-ff4fdf6c61ee.png)

**Comment by nkbt** [comment] 2015-10-19 00:33
@koko236 I have very little understanding of your structure, but it seems that the best solution would be to not apply react-motion directly to OtherUI, but make a very basic UI wrapper and apply react-motion to it. So you component that handles some actual data is not touched by RM and is totally "cached" by react. It also will have a huge impact on perf (in a good way).

**Comment by nkbt** [comment] 2015-10-19 00:35
The generic rule-of-thumb for me is - if it is not animated, do not animate it. So re-render only that little animated piece and abstract all the bigger logic not related to animated part into a separate component.

**Comment by koko236** [comment] 2015-10-19 00:56
Well, I might be abusing the React a little bit, but I'm using it for a windows like interface (can't show it at the moment though). So all the elements under `OtherUI` have `position: absolute` which is stored in UIStore and changed according to user interactions, i.e. drag and drop. Each draggable component is wrapped in a `Spring` to achieve smooth motion. The `Messages` are virtually independent except they bouth use React to render and looking at the call stack it seems like both mutations (Motion anim and adding a `Message`) get batched together and interfere with each other somehow. 

(I'm quite new to React so the above is not a very in-depth analysis of what goes on under the hood obviously :) 

On a more general note, I spent some time wondering how to organize the data flow to avoid massive updates during dragging (ATM, the whole draggable elements tree is updated with one general UIStore `CHANGE` event), but got convinced that the virtual DOM resolution in React is fast enough and it indeed seems to be the case even without using immutables for the state. Everything worked quite allright until I mixed React Motion transitions with adding new elements. I still hope there's some weird/stupid thing I did my code that I can fix easily, but I'm still trying to narrow down the problem.

**Comment by nkbt** [comment] 2015-10-19 01:02
@koko236 look at https://github.com/gaearon/react-dnd

Ping me in Slack (reactiflux), I can help you with your issue better there.

**Comment by koko236** [comment] 2015-10-19 01:18
I looked at DND (and will again for sure) but my knowlege of react was way lower at that moment and I decided to build something myself from scratch as a way of learning. Right now I don't think my problems are very much d'n'd related - anyway it's a good pointer, thanks. 

As to reactiflux - it's closed for new members now (http://www.reactiflux.com/)

**Comment by chenglou** [comment] 2015-10-19 01:34
Reactiflux is moving to Discord. Does this invitation link work? https://discordapp.com/invite/0ZcbPKXt5bYzmcI0

**Comment by koko236** [comment] 2015-10-19 01:41
Yes! Thanks.

**Comment by koko236** [comment] 2015-10-19 02:30
It might be too early to open the champagne but putting `MessagesStore` emitChange into setTimeout() with 0 delay 'solved' the problem - I was unable to break it anymore. I can imagine there is some race condition inside React.

**Comment by nkbt** [comment] 2015-10-19 02:47
@koko236 you quiclky patched the problem but did not solve the root cause. As I can see the cause is that your animation logic affects components that work with data/events (possibly re-renders them thousands of times). I strongly suggest you to remove setTimeout and figure out how to fix it without this hack =)

**Comment by koko236** [comment] 2015-10-19 03:00
I know it's just a patch and I hope it'll work cause I'm a bit time constrained right now. :) I'm wondering what the root cause might be and is it really something on my side. Truth is I should probably use raf to fire update events and not mousemoved event directly but the bug happens after the dragging has ended and it's only React Motion that modifies anything when `addMessage' is called (and that's an extremely simple operation).

**Comment by nkbt** [comment] 2015-10-19 03:06
@koko236 I'm just trying to help you to get an idea where the actual problem is. This issue has definitely nothing to do with react-motion itself, it is more about the way your code was structured, RM probably revealed that issue by constantly re-rendering things. If you are happy with a temp hack and it is a considered choice - that is totally all right.

If you wish to drill further - ping me on Discord (`@nkbt` there). And just in case add console.log into your `render` method so you can see it is actually rendered bazillion of times =)

**Comment by koko236** [comment] 2015-10-19 03:19
It sure as hell is. Thanks a lot, I'm switching to Discord.

**Comment by chenglou** [comment] 2015-11-20 22:30
Hi. Is this issue resolved?

**Comment by koko236** [comment] 2015-11-22 12:37
Hi, it's worked around for now but I had no time to seek the root cause of the problem.

**Comment by chenglou** [comment] 2015-11-25 08:37
Alright then. Weird stuff!
Closing for now =)

**Closed by chenglou** 2015-11-25 08:37 UTC
