### ISSUE TITLE
React-motion doesn't work with Radium

### ISSUE THREAD

**Issue by yanivtal** [chenglou/react-motion#89] opened 2015-07-21 02:50 UTC
Radium's a project for inlining styles with react. When I use the @Radium decorator I get the following Javascript error from the Spring's render method.

```
Uncaught TypeError: this.props.children is not a function
```
in the following code
```
render: function render() {
    var currVals = this.state.currVals;

    return _react2['default'].Children.only(this.props.children(currVals));
  }
```
React-motion works without Radium and Radium works without react-motion. Here's my render method:
```
render() {
    return (
      <Spring className="box" endValue={{val: this.state.isClosed ? 1 : 0, config: [90, 18]}}>
        {({val}) =>
            <img src={this.props.img}
                 style={[styles.img, this.imgStyle(val)]}
                 onMouseDown={this.handleMouseDown.bind(this)}/>
        }
      </Spring>
    );
  }
```
Any thoughts?

**Comment by nkbt** [comment] 2015-07-21 03:12
Do you have a reproducible example somewhere? Maybe your code is compiled in some awkward way so it is not a function anymore that is passed to Spring... 
Check your actual built bundle first

**Comment by chenglou** [comment] 2015-07-21 03:57
This is the expected behavior. You're asked to provide a single child as a return value to `Spring`'s children prop. Radium does something funny with the children?

**Comment by threepointone** [comment] 2015-07-21 04:54
can you show the radium integration too? we should come up with a generic solution/workaround to avoid this problem with components that rewrite children.

**Comment by yanivtal** [comment] 2015-07-21 15:42
Where do you post fiddles with react 0.13 and react-motion?

The Radium integration is simply achieved with a decorator:
```
@Radium
export default class TechnologyBox extends Component {
```
You take styles like:
```
const styles = {
    img: {
      width: 1000 / 4 - 15 + 'px'
    },
```
and then pass in an array of styles to a component. In the example I showed I had:
```
<img src={this.props.img}
                 style={[styles.img, this.imgStyle(val)]}
                 onMouseDown={this.handleMouseDown.bind(this)}/>
```
where styles.img is the style object and this.imgStyle(val) returns a style object using Spring's val. Both of these are plain style objects and should be concatenated by Radium.

You can see from my example that I do have a single function as the child of the Spring.. Any help would be appreciated.

**Comment by threepointone** [comment] 2015-07-21 17:34
This seems more like an issue with the way radium rewrites a render tree. I'll have a look sometime this week, but could you file an issue on the radium repo as well?

**Comment by yanivtal** [comment] 2015-07-21 18:56
Just did. He says it's fixed on master. Thanks! I'm fine closing this ticket or you use this to track implementing a generic solution to working with components that rewrite children.

**Comment by chenglou** [comment] 2015-07-21 19:14
The `children.only` pattern is/will be used but lots of libraries in conjunction with propTypes. Rewriting it and breaking the contact isn't something we should handle imo. So closing this because it's not react-motion specific and we don't wanna handle these =).

**Closed by chenglou** 2015-07-21 19:14 UTC

**Comment by threepointone** [comment] 2015-07-22 04:06
I had a look at the radium tracker, and it seems like their fix is to ignore components with fn-children o_O. unfortunate result of the way it works internally, so there's not much we can do anyway. @yanivtal, as a quick workaround for your case, I'd recommend using something simpler like css classes / plain objects for the components you're animating.

**Comment by yanivtal** [comment] 2015-07-23 04:21
@threepointone That's what I'm thinking. I don't really need radium for that. Thanks. You're quick with it!
