### ISSUE TITLE
Document the difference with easing + duration

### ISSUE THREAD

**Issue by AlexGalays** [chenglou/react-motion#113] opened 2015-08-02 16:31 UTC
Hello,

Would it be possible to document the differences between the easing + duration and the stiffness + damping models? Is there a roughly equivalent setting to the common easing curves?

**Comment by chenglou** [comment] 2015-08-02 20:37
The brief version is [here](https://github.com/chenglou/react-motion/blob/f774ae5c0a099b40229ce09754e2128fb2f5ca3f/README.md#what-does-this-library-try-to-solve). To make picking your spring constants more intuitively I've made [this](https://cdn.rawgit.com/chenglou/react-motion/c3c5403b6821b7a8954e3c379057ae7d9bbc39d5/demos/demo5/index.html). #68 also talks about it.

I'm leaving this issue open because it's a good idea to write a fuller description in the upcoming doc site =).

**Comment by chenglou** [comment] 2016-04-20 02:50
This issue has been open for a while now. I think by now https://github.com/chenglou/react-motion/tree/089adea6d7d1b6fc6acf450eb63917f735980dc1#what-does-this-library-try-to-solve makes it clear enough why a spring is desirable. I have less time to work on an actual doc site now but the problem is comparatively small enough for me to close this issue. 

Thanks for filing it; I'll still keep this in mind. #302

**Closed by chenglou** 2016-04-20 02:50 UTC
Labels: question
