### ISSUE TITLE
Demo3 (todoList), TransitionMotion: "defaultStyles" and "styles"  => got object, array expected

### ISSUE THREAD

**Issue by MadeInMoon** [chenglou/react-motion#319] opened 2016-04-09 01:12 UTC
I'm adapting react-motion (stable) [demos](https://github.com/chenglou/react-motion/tree/0627243316c564f6c2f480bf615b82135f649a0a/demos)  in our very new [template app](http://template-meteor-react.meteorapp.com/showcase) (meteor-react-es6), to transform each of them in a single component (ex: `<DraggableList/>`), using [react-motion](https://www.npmjs.com/package/react-motion) npm package and `React.Component` (instead of `React.createClass`).

So it only demands a syntax adaptation, but variables still the same..

**The original file**

[demo3/](https://github.com/chenglou/react-motion/blob/0627243316c564f6c2f480bf615b82135f649a0a/demos/demo3/Demo.jsx)

**My component**

[here](https://gist.github.com/MadeInMoon/363d4a2d3eef1a73fc399eaa9dd5ce52)
(shortcut to [TransitionMotion](https://gist.github.com/MadeInMoon/363d4a2d3eef1a73fc399eaa9dd5ce52#file-react-motion-transitionmotion-jsx-L171))

**Console**

`Warning: Failed propType: Invalid prop "defaultStyles" of type "object" supplied to "TransitionMotion", expected an array. Check the render method of "ListAnimated"`

`Warning: Failed propType: Invalid prop "styles" supplied to "TransitionMotion". Check the render method of "ListAnimated"`

Error `Uncaught TypeError: defaultStyles.map is not a function`

Any idea guys??

**Comment by liyaodong** [comment] 2016-04-14 03:26
Same problem, is this project alive?

**Comment by nkbt** [comment] 2016-04-15 03:58
@MadeInMoon, I've just double-checked 0.4.1 version locally and had no issues with current demo3. The problem is definitely somewhere in your adaptation. Could you please post your component to Codepen so we can run it?

**Comment by nkbt** [comment] 2016-04-15 04:01
```
  // actual animation-related logic
  getDefaultValue() {
    const {todos} = this.state;
    return Object.keys(todos)
      .reduce((configs, date) => {
        configs[date] = {
          height:  spring(0),
          opacity: spring(1),
          data:    todos[date],
        };
        return configs;
      }, {});
  }
```

```
  getDefaultStyles() {
    return this.state.todos.map(todo => ({...todo, style: {height: 0, opacity: 1}}));
  },
```


`getDefaultStyles` returned array of styles. `getDefaultValue` returns object. Object does not have `map` method.

**Comment by MadeInMoon** [comment] 2016-04-15 09:43
Problem solved.. Man, thank you so much for helping..

**The problem**
I was adapting the demo3/todo from [this commit](https://github.com/chenglou/react-motion/tree/0627243316c564f6c2f480bf615b82135f649a0a/demos), after reading that in master demo readme:

`Note: since this is the master branch, the demos might be a bit ahead of the current stable API. This commit contains the [stable demos](https://github.com/chenglou/react-motion/tree/0627243316c564f6c2f480bf615b82135f649a0a/demos).`



**Your Solution**
the demo3/todo from master  [demos](https://github.com/chenglou/react-motion/tree/master/demos)


-------------

**Question**

In the stable commit : 
    - demo8 :  re-adaptable in a few seconds
    - demo3 : seems to be un-usable because of object/array formats

Is it better to go in master  [demos](https://github.com/chenglou/react-motion/tree/master/demos) or [stable commit demos](https://github.com/chenglou/react-motion/tree/0627243316c564f6c2f480bf615b82135f649a0a/demos)?

**Comment by nkbt** [comment] 2016-04-16 06:48
Master of course.

Why changing demos to es6 classes?

**Comment by MadeInMoon** [comment] 2016-04-16 10:14
All my template app components are ES6 consts or classes. So why should stay in ES5?

**Comment by nkbt** [comment] 2016-04-19 23:26
@MadeInMoon ah, sorry, I thought you are going to PR these changes to `react-motion`.

I am closing this for now, feel free to ping me in https://gitter.im/nkbt/help or Reactiflux if you need more help!

**Closed by nkbt** 2016-04-19 23:26 UTC
Labels: question
