### ISSUE TITLE
willLeave 里 console.log('leave') 时发现 requestAnimationFrame 没有被取消

### ISSUE THREAD

**Issue by Lucifier129** [chenglou/react-motion#15] opened 2015-07-07 08:45 UTC
在 demo3 的 RedoMVC 中修改：
```javascript
willLeave(date, update, destVals, currVals) {
    console.log('leave')
    if (currVals[date].opacity > 0) {
      return update({
        height: 0,
        opacity: 0,
        data: update(currVals[date].data, -1, -1),
      });
    }
  },
```
在切换 filter 时发现，一旦触发 willLeave 后，不做其他操作，console 将无限打印。

另外，在我个人实现的 todomvc demo中，删除 todo 的方式不是以 height:0px 来表示的，而是 removeChild ，在 react-animation 里暂时没有找到在动画完成后决定是否删除元素的方法。

**Comment by chenglou** [comment] 2015-07-08 07:02
I'll answer in English for the sake of people searching for this issue.

Your issue is that the console logs "leave" infinitely, I'm not sure what you mean by that because currently it does stop after a while. If you're talking about `willLeave` being triggered many many times for a same component, this is the expected behavior. It will keep asking you whether the component should be unmounted, **until you return `null`** (aka, "yes, do it now". This should answer your second question). I actually think is one of the biggest differentiator vs TransitionGroup. It also theoretically decouples the unmounting logic with the animation logic.

For other frameworks' TodoMVC, yes, you _do_ do the imperative `removeChild`. But this is extremely error-prone and not idiomatic react at all.

I'm glad to see people fearlessly cloning and playing around with my undocumented stuff though, thanks =). Closing this unless you have further questions!

**Closed by chenglou** 2015-07-08 07:02 UTC
