### ISSUE TITLE
Migrate from React.createClass

### ISSUE THREAD

**Issue by sjogren** [chenglou/react-motion#448] opened 2017-04-11 13:17 UTC
If [React v15.5.0](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html) is used you get the following warning:

`Warning: Motion: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.`

See [Migrating from React.createClass](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.createclass).

**Comment by olegkogan** [comment] 2017-04-11 20:11
The same thing.

**Comment by MichaelDeBoey** [comment] 2017-04-12 15:28
Dupe of #445

**Closed** 2017-04-13 00:43 UTC
