### ISSUE TITLE
warning: setState(...) if component is unmounted while Motion is still active

### ISSUE THREAD

**Issue by Aranir** [chenglou/react-motion#316] opened 2016-04-05 12:48 UTC
We are using React Bootstrap with React Motion.

When we animate the appearing of items on a Modal Component and during the animation close the modal the following message gets logged continuously into the console:

```
warning.js:45 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Motion component
```

It appears that the Motion component still calls update state although the component is unmounted (we use React v0.14)

Before the message gets logged into the console the component unmounts, is there a possibility to stop the Motion component?

If the error message would be only once its fine, but it gets continuously logged to the console and the Motion components apparently never stops updating its state.

**Comment by nkbt** [comment] 2016-04-06 01:36
That is and issue with Modal component. It unmounts element without waiting until animation is finished (or killing animation). Quite common issue I often run into myself.

Since even I run into that often, I could only imagine how common this issue is... Maybe it is worth adding some safeguard in ReactMotion itself. Though It is not really a fixing of root cause of the issue, but rather patching over unsafe implementations.

@chenglou any thoughts on this?

**Comment by MadeInMoon** [comment] 2016-04-08 21:18
@Aranir 
I had the same issue with the demo8 (draggable list) because of **event listeners** set up in componentDidMount().
I fixed that adding `removeEventListener`  in `componentWillUnmount()`

hope it can help

**Comment by Aranir** [comment] 2016-04-13 15:06
Unfortunately this doesn't resolve my issue, if the component is closed during the initial setup, where they still animate to the right position, it's not triggered by any eventlistener.

**Comment by souporserious** [comment] 2016-05-27 23:05
I believe this should have been fixed with https://github.com/chenglou/react-motion/pull/305

**Comment by chenglou** [comment] 2016-08-13 08:14
Closing. If this reappears, feel free to reopen!

**Closed by chenglou** 2016-08-13 08:14 UTC
