### ISSUE TITLE
Sequence 

### ISSUE THREAD

**Issue by khankuan** [chenglou/react-motion#236] opened 2015-11-03 16:41 UTC
Hi, I have a list view and a desired animation in this sequence:
1) item is delete, it fades out to 0.
2) items are rearranged, where items below the deleted item translates upwards.

How can I achieve a "sequence" of animations?

Thanks!

**Comment by nkbt** [comment] 2015-11-03 23:14
It looks like a duplicate of #224 and blocked by #235

**Comment by chenglou** [comment] 2015-11-25 08:35
Yep. Closing in favour of #224!

**Closed by chenglou** 2015-11-25 08:35 UTC
