### ISSUE TITLE
Is it possible to optimise demo8-draggable-list so it could work with many items?

### ISSUE THREAD

**Issue by Cottin** [chenglou/react-motion#267] opened 2016-01-26 14:32 UTC
demo8-draggable-list works beautifully with 4 items even on mobile devices.

However, if you increase the items to like 100, it starts lagging noticeably on desktop and pretty much on mobile.

I'm guessing sorting of a list like this is quite a common use case so I was wondering if you know of any tricks of optimising demo8-draggable-list so that it could handle more items? Or is it at all possible to do this kind of re-ordering of large lists with react-motion on a mobile device?

(maybe related to #37 ?)

**Comment by chenglou** [comment] 2016-01-27 03:45
(Don't forget to profile on prod build. Dev build means nothing).

The problem is that the current simplistic logic of the demo updates the whole owner component (including your hundreds of other unaffected items) while dragging. The animation itself, upon release, is still 60fps.

This happens with any naive drag & drop implementation such as the one in this demo (where I aimed for ease of reading more than anything else).

The solution is most likely putting some clever `shouldComponentUpdate`. For example, have the owner track which items are likely affected, and only update those (by passing down a prop).

Most likely related: #244

**Comment by Cottin** [comment] 2016-01-27 15:05
How do you easiest test a prod build?

`npm run prerelease` gives a `lib` folder with library stuff (no examples).
`npm run build-demos` gives a `build` folder, but which `index.html` should you use to run it if you start up a little `http-server` or similar?

**Comment by nkbt** [comment] 2016-01-27 20:27
You can run demos as static html. No server required.

**Comment by chenglou** [comment] 2016-01-27 22:13
Good point, tweaked the README.

**Comment by Cottin** [comment] 2016-02-02 10:18
Thanks for README clarification!

I did a quick try to optimise the demo a bit.
Could you give any comments to what you think of my approach?

1. For simplicity I'm only animating the y positions, thus leaving out scale and shadow.

2. Create a new component `Motion2` that wrapps `Motion` and implements a stupid `shouldComponentUpdate` that only looks at the y position:

```
import lo from 'lodash';
import R from 'ramda';

const Motion2 = React.createClass({
  shouldComponentUpdate(nextProps, nextState) {
    return !lo.isEqual(this.props.style.y, nextProps.style.y)
  },

  render() {
    const propsToRender = R.evolve({style: R.dissoc('stopRender')}, this.props);
    return (
      <Motion {...propsToRender} />
    )
  }
})
```

With this approach I could have 100 items flow pretty decently on an iPhone 6.

When you go up to 500 items it starts lagging a lot. However I did notice that it looks like the bottleneck with 500 items lies in React's reconciliation or whatever you call it because if I `return false` in `shouldComponentUpdate` for the items with an index  `> 10` it still lags.

So it looks like to just go through 500 items and call `shouldComponentUpdate` on all of them is too slow in itself in React. Note that 10 of these items gets re-rendered and 490 of them always returns false from `shouldComponentUpdate`.

Do my findings sound correct to you or am I messing something up? Could you maybe direct me to how I should continue this work? :)

**Comment by chenglou** [comment] 2016-04-19 23:00
(Sorry for the late reply) Seems fine. Also, you can look into the convenience https://github.com/reactjs/react-static-container. It likely doesn't make your situation better, but it's there.

Closing this as this is "solved". Another closed issue in my misguided quest to reduce issue count =]. Feel free to keep the discussion going!

**Closed by chenglou** 2016-04-19 23:00 UTC

**Comment by brownieboy** [comment] 2016-12-06 10:53
@Cottin,

I was able to get okay performance with 500 items on an iPhone 6, using the technique that you've outlined above.  See [Demo](http://www.users.on.net/~mikeandgeminoz/code/react-motion-8a-listwithhandle/).

This is part of variation on the draggable list demo that I'm working on.  The variation here is that items in the list are only draggable by their drag handles (the icon with the three lines).

I don't have the code on Github yet, but you can read the source code in the browser.
