### ISSUE TITLE
Warning in React.StrictMode

### ISSUE THREAD

**Issue by xiaody** [chenglou/react-motion#559] opened 2018-11-15 03:28 UTC
```
componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: Motion, TransitionMotion

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
```

- https://github.com/chenglou/react-motion/blob/v0.5.2/src/Motion.js#L213-L224
- https://github.com/chenglou/react-motion/blob/v0.5.2/src/TransitionMotion.js#L507-L530

**Comment by nkbt** [comment] 2018-11-15 10:29
There is a PR https://github.com/chenglou/react-motion/pull/534 already. I haven't seen much real world testing on it yet and not sure how much stuff is going to be broken unfortunately =(

**Comment by xiaody** [comment] 2018-11-16 03:02
Well, if there isn't a release, how can anyone easily test on it? What about a test release like `0.6.0-alpha.0`?

**Comment by nkbt** [comment] 2018-11-16 11:41
one can always install it from pr/git hash, it is not necessary to release to test it,

**Comment by xiaody** [comment] 2018-12-10 07:09
A test release indicates that is official and at least well reviewed. Never mind, I have moved to https://github.com/drcmda/react-spring.

**Comment by nkbt** [comment] 2021-02-25 03:40
Close as duplicate of https://github.com/chenglou/react-motion/issues/569#issuecomment-780190833

**Closed by nkbt** 2021-02-25 03:40 UTC
